# Generated by Django 5.0.6 on 2024-08-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('emailid', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(blank='false', max_length=50, null=True)),
                ('Address', models.TextField()),
                ('Position', models.CharField(max_length=50)),
                ('Employment', models.CharField(max_length=6)),
                ('Dateofjoining', models.TextField()),
                ('Employmentid', models.CharField(max_length=50)),
                ('Highestqualification', models.CharField(max_length=50)),
                ('Institution', models.CharField(max_length=50)),
                ('Yearofgraduation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HallTickectnumber', models.CharField(max_length=20)),
                ('Student_name', models.CharField(max_length=50)),
                ('Father_name', models.CharField(max_length=50)),
                ('Mother_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6)),
                ('Address', models.TextField()),
                ('Zincode', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=50)),
                ('Yearofpassout', models.CharField(max_length=50)),
                ('Enroll_date', models.DateField()),
                ('Course_duration', models.CharField(max_length=50)),
                ('Moblie', models.CharField(max_length=50)),
                ('Emergengynum', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
