# Generated by Django 5.0.6 on 2024-08-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.CharField(max_length=10, null=True)),
                ('emailid', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(blank='false', max_length=50, null=True)),
                ('Address', models.TextField(null=True)),
                ('Position', models.CharField(max_length=50, null=True)),
                ('Employment', models.CharField(max_length=6, null=True)),
                ('Dateofjoining', models.TextField(null=True)),
                ('Employmentid', models.CharField(max_length=50, null=True)),
                ('Highestqualification', models.CharField(max_length=50, null=True)),
                ('Institution', models.CharField(max_length=50, null=True)),
                ('Yearofgraduation', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
