# Generated by Django 5.0.6 on 2024-08-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staff1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('fathername', models.CharField(max_length=100, null=True)),
                ('mothername', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('name_course', models.CharField(max_length=100, null=True)),
                ('coursecode', models.CharField(max_length=10, null=True)),
                ('course_duration', models.IntegerField(null=True)),
            ],
        ),
    ]
